app = "milk-run"
primary_region = "yyz"

[build]

[env]
  PHX_HOST = "milkrun.rocks"
  PORT = "8080"
  ECTO_IPV6 = "true"
  ERL_AFLAGS = "-proto_dist inet6_tcp"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/"
